.travis.yml, Pipfile, README.md, mcm/ascvd_outcome_model.py, mcm/outcome_model_repository.py, mcm/person.py, mcm/test/test_nhanes_linear_risk_factor_model.py, mcm/test/test_risk_model_repository.py, mcm/test/test_statsmodel_linear_risk_factor_model.py
This PR:
- adds linting and formatting scripts to Pipfile.
+ `flake8` can now be run with `pipenv run lint`.
+ `autopep8` can be run with:
* `pipenv run format-diff` to see a diff with the proposed formatting changes without actually making them, or
* `pipenv run format` to actually make formatting changes to the code.
- adds a lint check in Travis, which will now fail the build if code does not pass `flake8`.
- adds a "Development Quickstart" section to the README that briefly describes how to setup a development environment for this repository.
=> Add linting & formatting to Pipenv & Travis

.travis.yml
Changes `.travis.yml` so that the build doesn't fail only if the lint fails. Figured that we would want to view lint errors but maybe not block only for formatting.
=> Don't fail CI build only for lint

.gitignore, .vscode/workspace-settings.example.json, Pipfile
Adds an example `settings.json` file (`workspace-settings.example.json`) for users of VSCode and its Python extension to use as a base. It should help users set up a decent development environment with VS Code much more quickly and easily than before.
=> Add sample VSCode settings.json file

Pipfile, Pipfile.lock
After freshly cloning the (now smaller) repository, I ran tests to verify everything was working correctly. However, upon doing so, several tests failed with  the following error:
```
$ pipenv run test
.
.
"/<path>/<to>/python3.6/site-packages/patsy/tokens.py", line 35, in python_tokenize
assert pytype not in (tokenize.NL, tokenize.NEWLINE)
AssertionError
```
Searching for the literal text of the error, I saw an issue that claimed this was due to a bug in `patsy`, a dependency of `statsmodels`, which is one of our dependencies. I regenerated `Pipfile.lock` to update `patsy` (among other dependencies) to a version with a fix.
On a more general note: using a lockfile is supposed to prevent issues this type of build reproducibility error by ensuring all machines have the same versions of all …
=> Update patsy (by regenerating Pipfile.lock)

mcm/model_argument_transform.py, mcm/statsmodel_cox_model.py, mcm/statsmodel_linear_risk_factor_model.py
This PR separates the logic that transforms model arguments for `StatsModelLinearRiskFactorModel` based on parameter name prefixes, making it more comprehensible and shareable. This feature enabled quick, simple changes to Person properties that were passed to models for risk factor and outcome evaluation, which made it easy to include new models, so it made sense to make it an official, shareable thing.
Transforms (at the moment, anyway) are simple: they're callables that take one value and return another, possibly to another transform. Which callables are applied and in which order is determined by prefixes attached to the model parameter name. The core of this logic lives in [`get_argument_transforms`](https://github.com/jburke5/mcm/compare/add-model-argument-transforms#diff-1ccc851e331 …
=> Add model argument transforms

mcm/model_argument_transform.py, mcm/statsmodel_linear_risk_factor_model.py
Follow-up on #6: convert all transforms to classes. This should make implementing new transforms and referencing existing ones easier because you don't have ask whether a transform is a class or a function or potentially consider the entire class of `Callable`s. This should also provide the basis to check that the inputs/outputs of transforms match before running the simulation proper, preventing runtime errors.
I'm not 100% happy with classes that don't have state, but the scoping and consistency added by making these classes outweighs that for me.
=> Class-based transforms

LICENSE.md, pyproject.toml
This PR makes explicit that this project is released under the MIT license by:
- adding a `LICENSE.md file`, containing the text of the MIT license (with a copyright date of 2021 and with Dr. Jim Burke as the copyright holder), and
- setting the `tool.poetry.license` field to `"MIT"` in `pyproject.toml` (which is/will be used to build the PyPI package)
We will want this to be able to accept contributions but also to allow people to start using the code if they so desire.
The only place I can think of the license needing to be changed outside of this PR is on the GitHub project page, though I also wouldn't be surprised (but don't know for sure) if GitHub has a scraper to automatically change it. Either way, I will make sure it is changed there as well after merging this PR.
=> Add license (MIT)

INSTALL.md, README.md
Add a simple installation guide for statisticians less familiar with the command line on setting up the project from scratch. This addresses the concern in issue #8, though no script because different systems have vastly different setup processes.
=> Add documentation on installing from scratch

microsim/person.py, microsim/test/test_gcp_model.py
This PR fixes that bug that could have prevented the implementation of individual-level random effects from working correctly.  It also adds a test to verify the fix.
Specifically, I noticed that [the `randomEffects` argument in `Person.__init__` had a dictionary as its default value](https://github.com/jburke5/microsim/blob/8a05645dfb180713b43351e9f577347dfd34fd41/microsim/person.py#L57), which [was then directly assigned to the `Person._randomEffects` property](https://github.com/jburke5/microsim/blob/8a05645dfb180713b43351e9f577347dfd34fd41/microsim/person.py#L121). Because default argument values are set when the function is defined rather than when it is called, every `Person` object instantiated without an explicit `randomEffects` argument would have a reference to the same …
=> Fix person random effects init

.vscode/settings.example.json, README.md, poetry.lock, pyproject.toml, scripts/format.py
This PR switches the code formatter for this project from autopep8 to [black](https://black.readthedocs.io/en/stable/).
Autopep8 was generally too reserved with changing code and with maintaining a consistent style. In contrast, black is prescriptive but consistent, and usually just works, so once adjusted to its style, should allow us to focus less on formatting and more on code.
My only slight reservation is that black is still in beta. However, [the PSF is now hosting it on GitHub](https://github.com/psf/black), and [a number of major Python projects are using it](https://github.com/psf/black#used-by) (e.g., SQLAlchemy, pandas, and Poetry), so major instability seems unlikely.
Draft PR #18 shows what the code in this repository would look like if it were formatted with `black`. You can …
=> Switch Code Formatter to Black

INSTALL.md, README.md, microsim/bp_treatment_strategies.py, microsim/gcp_model.py, microsim/gfr_equation.py, microsim/model_argument_transform.py, microsim/population.py, microsim/statsmodel_cox_model.py, microsim/test/test_dementia_model.py, microsim/test/test_outcome_repository.py, microsim/test/test_person_advance_outcomes.py, microsim/test/test_statsmodel_linear_risk_factor_model.py, poetry.lock, pyproject.toml
This PR contains two fixes related to the recent dependency update and Python 3.9 upgrade:
1. Updates `README.md` and `INSTALL.md` to reflect the new Python major version (3.9), and
2. Updates `black` to a new major version to fix a bug that prevented it from running. (This PR also contains the formatting changes from running the new version of `black` on this repository.)
Details for #&#8203;2: `black` 21.11b was incompatible with a newer version of one of its dependencies (`click` 8.1.3), which was likely installed either when updating dependencies or when upgrading to Python 3.9. A fix was available in `black` 22.3.0, and while a patch fix was technically possible, the major version was updated instead to (finally) move onto stable releases of `black`.
=> Fixes Following Python 3.9 Upgrade

poetry.lock, pyproject.toml
toml and lock files were modified: Updated the python version, and included the ipykernel and matplolib in dependencies. This allows the microsim installation on MacOS and the creation of a microsim kernel for Jupyter notebooks.
=> updated toml file

microsim/population.py
On line 171 in population.py, variable newDementia was used but there was a possibility that that variable would not be defined prior to line 171, which would kill the simulation. Changed newDementia to alive['dementiaNext'] which is always defined.
=> fixed bug on line 171 population.py

microsim/trials/linear_regression_analysis.py, microsim/trials/logistic_regression_analysis.py, microsim/trials/outcome_assessor.py, microsim/trials/regression_analysis.py, microsim/trials/trial.py
Implemented a method in RegressionAnalysis that returns the absolute effect size of a trial (risk difference in logistic, attribute mean difference in linear). The method needs to get the dataframe that the get_dataframe produces (implemented in RegressionAnalysis as well). I am using mean() for both logistic and linear regression.
I added dtype=int just to reduce the probability the conditional statement is not evaluated correctly. 
In the code I had to review for this task, I have added a few comments on what assumptions are made in other parts of the code (to decrease probability things break down later and to spend less time in the future when I need to work on this code again).
A thought/question: It seems to me that OutcomeAssessor was designed to return a binary outcome which is a …
=> get absolute effect size from trials

microsim/population.py, microsim/sim_settings.py
overall: implemented a flag to turn on/off pandarallel
1) created sim_settings.py and a class simSettings with this flag
2) modified population.py to use this flag and tested that it works 
With this implementation, every population instance can change its usage of apply/parallel_apply at will. We could also move, perhaps, the if-else statements on applyMethod in the simSettings class but we would not be able to control then
how each instance uses apply/parallel_apply.
=> implemented a flag to turn pandarallel on/off

microsim/trials/attribute_outcome_assessor.py
Overall: implemented change in attribute assessment methods. 
One method tests for the change in attribute being greater than a parameter, and another method tests for the
change in attribute being less than a parameter. 
Both of these tests could have been implemented by a single method, but this would place a greater burden on the user to negate the outcome when they wanted the comparison operator that was not implemented.
=> implemented change in attribute assessment method

microsim/population.py, microsim/trials/trial.py, microsim/trials/trial_description.py, microsim/trials/trial_utils.py, microsim/trials/trialset.py
Trialset was modified to support both a serial and an efficient parallel trialset run method.
Added a TrialsetSerial subclass that runs trials in a serial manner.
Added a TrialsetParallel subclass that runs trials in a parallel fashion.
The two subclasses return results in an identical format, but the TrialsetParallel subclass requires an extra argument for input (number of processes to be launched).
Possibility: TrialsetSerial and TrialsetParallel run methods could be moved to Trialset which could take an extra
optional argument (number of processes), which could be used for Trialset to decide whether to use the serial or the parallel run method.
Possibility: some work that the user needs to do know on the control of pandarallel can be included in the Trialset subclasses.
The prior …
=> added support for parallel trialsets

microsim/trials/trial.py, microsim/trials/trial_utils.py, microsim/trials/trialset.py
The method analyzeSmallerTrials was overwriting the analysis results for the smaller trials because there were multiple dictionary keys with exactly the same sample size and there was no way to distinguish between them. I added a sampleSizeIndex to help distinguish the analysis results of smaller sample sizes. This sampleSizeIndex is not reported on the results dataframe, is only used in the key. The analysis of the max sample size was reported without problems because there was only one.
=> stopped overwriting smaller sample trial results

microsim/test/test_population_reporting.py, microsim/test/test_treatment_strategy.py
Some tests were always using person 0 and occasionally that person was dying before the end of the simulation, which resulted in sometimes the tests returning False...I have them now check for all people in the population, not just 1, under the condition they were alive at the end of the simulation...
=> fixed tests

microsim/test/test_treatment_recalibration.py, microsim/trials/linear_regression_analysis.py, microsim/trials/logistic_regression_analysis.py
Removed an argument from trial logistic and linear regressions that was supposed to suppress warnings but ended up creating new warnings....also changed 2 iteritems to items....
=> stopped warnings from regression optimizer

microsim/bp_treatment_strategies.py, microsim/population.py, microsim/test/test_overall_population_function.py
We discovered that modelEstimatedRR was always 1 because the estimated risks in the untreated and treated columns were identical due to the estimate_risks method using *last values whereas all the updates were existing on *Next values.
So, the code now moves the *Next values as they become available in two groups, risk factors and treatment, outcomes. All estimated risk methods should now use the *last values which are also the latest ones.
The move_people_df method was broken in two methods, one for risk factors and treatment and one for outcomes.
I have added several comments in advance_vectorized to help me remember how this is  organized, what is happening etc.
I have also reorganized some calculations in advance_vectorized, eg grouped some outcomes, etc, not sure how helpful this …
=> Model estimated RR bug in recalibration (fixes #40)

microsim/trials/trial.py
The while loop was copying only the first person of the population in both the treated and untreated populations, so each population included only 1 unique NHANES person (copied over as many times as maxSampleSize). 
Since we are using thresholds in trials, it may be useful to know the number of unique NHANES indices that participate in trials, so trials now report that for both treated and untreated.
=> removed while loop in trial.randomize method, report unique NHANES index in trials
